version: "3.8"

services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mongodb
    env_file: mongodb-config.env
    networks:
      - mongodb_network
    ports:
      - 27017:27017
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    env_file: mongo-express-config.env
    volumes:
      - mongodb-data:/data/db
    depends_on:
      - mongodb
    networks:
      - mongodb_network
    ports:
       - 8181:8081
    healthcheck:
      test:  wget --quiet --tries=3 --spider http://admin:admin123@localhost:8181 || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
volumes:
  mongodb-data:
    name: mongodb-data
networks:
  mongodb_network:
    name: mongodb_network